<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Subject</name>
   <tag></tag>
   <elementGuidId>97933d3a-1dd6-45ef-96ce-8b75909c0fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.Subject.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='supportCover']/div[2]/sec-form/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1631b6ba-5215-47d5-b4ea-c101193080ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Subject ng-binding</value>
      <webElementGuid>45e45e86-1aad-490c-93f4-f64210fb972b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>* Subject</value>
      <webElementGuid>ecfeb705-23ad-4d7c-9939-68039b6700c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supportCover&quot;)/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;splitter&quot;]/div[@class=&quot;smollPadding  margin-right&quot;]/label[@class=&quot;Subject ng-binding&quot;]</value>
      <webElementGuid>ca3a6fb0-2a83-412a-a57f-f2fccfb3c1eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supportCover']/div[2]/sec-form/div[2]/div/label</value>
      <webElementGuid>fbbd799d-04d6-4271-8d64-a4500dab70b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sec-form/div[2]/div/label</value>
      <webElementGuid>e0370a4e-9ee0-470f-a412-2ace3667af20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '* Subject' or . = '* Subject')]</value>
      <webElementGuid>9ad1064c-ac7e-4c9a-aadf-bee322defb30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
