<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_loader</name>
   <tag></tag>
   <elementGuidId>31b5837b-1a3f-432c-a4b1-032ac1fcc4b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > div.loader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a1b8549-59d8-489c-84d8-77627234ea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loader</value>
      <webElementGuid>6f840015-625c-406f-a5fa-202a708a814a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/login-modal[1]/div[@class=&quot;PopUp&quot;]/div[1]/div[@class=&quot;loader&quot;]</value>
      <webElementGuid>c69414c4-b08a-4f00-be53-3f638e41f31e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>4b3322a3-3729-424a-ac29-1d1b390997fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
