<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit shipping details</name>
   <tag></tag>
   <elementGuidId>0b8d1ce4-5c7c-4c85-a1d3-4662e79d6f64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.blueLink > a.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userSection']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da81ea2c-7a43-41a7-955b-cf11d342f822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>7bfb37ab-fed5-476a-bef7-91c9f2c2dae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setUserDetailsEditMode()</value>
      <webElementGuid>c88d7ade-3010-4274-b8e6-4f0df77f70d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Edit_shipping_Details</value>
      <webElementGuid>6fa2bf9c-6bd8-4cec-84dc-c801dc825101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>aa103b28-309a-4b74-80bf-ab937d485f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>303e4a55-3edb-4f3f-a0c2-2f50cd029b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit shipping details</value>
      <webElementGuid>40be8a9a-f0d7-4008-a5c6-6391e62baa44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userSection&quot;)/div[1]/div[@class=&quot;blueLink&quot;]/a[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>65c2c782-1241-4951-b0d0-d9d5f3fc9e64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userSection']/div/div[2]/a</value>
      <webElementGuid>7c8e555a-99c1-4452-9acf-08194b25da1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit shipping details')]</value>
      <webElementGuid>240bef7f-5b0f-4591-9f6f-75d73d08f83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[12]</value>
      <webElementGuid>e6dfb87e-3063-46cf-9b4b-bbee333252af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/a</value>
      <webElementGuid>dbcfaff8-776a-4e92-b4ab-2ca15efb8611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Edit shipping details' or . = 'Edit shipping details')]</value>
      <webElementGuid>d7e59098-5590-49cb-b33b-044b5b2742c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
