<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NEXT</name>
   <tag></tag>
   <elementGuidId>a29c86aa-42d7-4f22-bfb8-96f4ef38f5fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sec-sender.roboto-medium.ng-isolate-scope.sec-sender > #next_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='next_btn'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1af7db58-a8ec-4873-b995-d327c58d47e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_btn</value>
      <webElementGuid>ae3d587c-23bf-41fe-8f85-290cf1835ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd2b40fb-9989-4ed8-9a66-e403bbc00482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sec-sender-a ng-scope</value>
      <webElementGuid>83f33676-94b5-412b-8d0b-862f0b325997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd086625-fe54-4de4-b914-b48d6277ff3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>senderCtrl.send()</value>
      <webElementGuid>af79963e-2b21-4b11-a932-ed546a8caafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>6331af53-a977-402c-a657-64e5df6a8c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDetailsEditMode&quot;)/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;blueLink&quot;]/sec-sender[@class=&quot;roboto-medium ng-isolate-scope sec-sender&quot;]/button[@id=&quot;next_btn&quot;]</value>
      <webElementGuid>a81317fe-cf89-44f6-bb7c-b6e5b04f6c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='next_btn'])[2]</value>
      <webElementGuid>c9c3d9b3-5046-4700-964c-472bc22bd1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userDetailsEditMode']/sec-form/div[7]/sec-sender/button</value>
      <webElementGuid>41105f34-4464-4f48-85a5-aae3795d958f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/sec-sender/button</value>
      <webElementGuid>eebdf0ac-7710-4af5-8b39-3bd65a8b4834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'next_btn' and @type = 'button' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>b13dbf8e-fcd5-4bd5-9bf6-f6aff6b7cf2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
