<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>344f2940-023e-4f0d-8238-bf03186b2aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.colors.ng-scope > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productProperties']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>171641d5-20fc-4442-9054-3d4b8957b2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!firstImageToShow</value>
      <webElementGuid>b81ff270-93b6-416d-bd74-8b6e0e4d7cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;colors ng-scope&quot;]/div[1]</value>
      <webElementGuid>b82817d6-5f33-4382-bedf-1091e5d5807d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div/div</value>
      <webElementGuid>c013934f-b1c0-4883-b1e7-bcacfee2fe5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>f2e10773-a7e8-43fe-8118-80dcd21542e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
