<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_loader</name>
   <tag></tag>
   <elementGuidId>232b16f4-5e3a-4d24-96e8-eca5787107b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.loader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e032540-9682-4e57-8eaf-8a232eb04433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loader</value>
      <webElementGuid>7b782493-cea4-4c6d-ad0d-c2d0ad8ab334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;loader&quot;]</value>
      <webElementGuid>1bae19cb-91ea-4fb8-9963-abf441c10d3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>9728c47b-781c-485d-a07f-c3ad94370c17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
