<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Color</name>
   <tag></tag>
   <elementGuidId>389244be-db87-4867-a06a-1a6af5bd20f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.Colors.roboto-light.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productProperties']/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8bdb4b2d-4e09-4ca7-9922-fb2f97d9479d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Color</value>
      <webElementGuid>b68a576d-d267-4a6a-b616-e74a40f73498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Colors roboto-light ng-scope</value>
      <webElementGuid>477beda2-8a23-4094-99a3-4c74d0d05a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Color:</value>
      <webElementGuid>ddc23c6c-760f-47c7-b2e5-24e804306788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;colors ng-scope&quot;]/h2[@class=&quot;Colors roboto-light ng-scope&quot;]</value>
      <webElementGuid>ec95f2f2-281c-4b49-bdc1-df24711784b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div/h2</value>
      <webElementGuid>4d8b0455-1510-4393-8299-2d8c31287158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h2</value>
      <webElementGuid>4e5d4ecc-0215-459a-891c-dd7fd3e27222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Color:' or . = 'Color:')]</value>
      <webElementGuid>7e1b911a-0309-407b-959c-61bf7332af74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
