<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Search result speakers</name>
   <tag></tag>
   <elementGuidId>4d30ef1b-b4b1-4185-aed3-73d9ac865e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchResultLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='searchResultLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0cb5ddbc-e2e4-408e-9848-6f9a69dcac35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchResultLabel</value>
      <webElementGuid>0e55015a-ae35-442f-b9f2-865ad1cc1f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular center sticky fixedImportant ng-binding</value>
      <webElementGuid>b881d186-a073-4b5e-9d32-d8fa551a28e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>noProducts</value>
      <webElementGuid>635afc82-7911-4192-aefa-ac6fa3f63904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search result: &quot;speakers&quot; </value>
      <webElementGuid>8a4bd77a-0089-4c37-89fe-50ca219115a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResultLabel&quot;)</value>
      <webElementGuid>485143d0-3e4e-4f42-b062-e4be9f5fd2fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='searchResultLabel']</value>
      <webElementGuid>37aad7f4-9b38-41bc-95d0-677a9fde9040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='searchPage']/h3</value>
      <webElementGuid>34c58424-d09e-47da-956d-944f336f0c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/h3</value>
      <webElementGuid>55a96bce-7925-4b26-8cd0-5edafd6b295d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'searchResultLabel' and (text() = ' Search result: &quot;speakers&quot; ' or . = ' Search result: &quot;speakers&quot; ')]</value>
      <webElementGuid>215d053c-e1a3-415e-aa82-1e3c0013eeac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
