<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputautoComplete</name>
   <tag></tag>
   <elementGuidId>fdf09d3b-d527-401a-9a11-727a222868a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autoComplete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autoComplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e12f2df-2a9e-44be-9c69-7745c623bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autoComplete</value>
      <webElementGuid>985f90a7-e213-4bd3-9098-4a5a77d1b021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aec6ff11-56f7-4008-82b9-0f64443d21b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular ng-pristine ng-valid ng-touched</value>
      <webElementGuid>64676b54-0fee-48cb-960c-4ad662e8d674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search AdvantageOnlineShopping.com</value>
      <webElementGuid>d8bc3a48-e71e-4a86-bd25-50fff6a42188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keypress</name>
      <type>Main</type>
      <value>checkEnterKey($event)</value>
      <webElementGuid>d7fa9949-aeea-44ec-82b9-ebde4d422b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>autoCompleteValue</value>
      <webElementGuid>90e5234d-e7a8-433e-a435-c53f81e694b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keyup</name>
      <type>Main</type>
      <value>runAutocomplete()</value>
      <webElementGuid>3bc14157-b1e9-48fb-81ac-c7bb0667efd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoComplete&quot;)</value>
      <webElementGuid>c0dbc256-f4e3-4bd6-8712-e0c4147802ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autoComplete']</value>
      <webElementGuid>d2a26b02-f4b9-4759-9e4e-ef360c566c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/input</value>
      <webElementGuid>10840035-6764-4f4a-836d-fbc1ac0fefc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>c5c3fdf9-232c-46c8-ae3d-6a1ec3d87aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autoComplete' and @type = 'text' and @placeholder = 'Search AdvantageOnlineShopping.com']</value>
      <webElementGuid>d4fbb265-1e5c-441d-b2c0-1424f38c3257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
