<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_speakers</name>
   <tag></tag>
   <elementGuidId>359b899e-cf38-442b-9427-fb6ca312688c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.roboto-light.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='output']/div/div/a/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9a47a368-06ac-4fe9-a4c2-8e6b5223d2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-light ng-binding</value>
      <webElementGuid>fea4d113-826a-4a99-b3ce-34378df686d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-mouseenter</name>
      <type>Main</type>
      <value>searchByCategoryId(result.categoryId, result.categoryName)</value>
      <webElementGuid>3b9b7996-68f3-4329-aa63-2ad41d36d076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        speakers
                    </value>
      <webElementGuid>7ddb291a-f30b-42f9-873e-6630dea69af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;output&quot;)/div[@class=&quot;searchPopUp&quot;]/div[@class=&quot;categories&quot;]/a[@class=&quot;ng-scope&quot;]/label[@class=&quot;roboto-light ng-binding&quot;]</value>
      <webElementGuid>45c653b9-e577-4c78-a4e1-ff222a814d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div/div/a/label</value>
      <webElementGuid>a9b0ad1f-3139-42d5-8a69-535041aee9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/label</value>
      <webElementGuid>d078b089-3fee-402b-9235-0589d281ac28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
                        speakers
                    ' or . = '
                        speakers
                    ')]</value>
      <webElementGuid>25ad5ebb-7f9e-40fe-a628-17d4f48201cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
