<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thank you for buying with Advantage</name>
   <tag></tag>
   <elementGuidId>8118910a-cad1-43b7-b5ee-7c12a513442f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.roboto-regular.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderPaymentSuccess']/h2/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ba3a9b5-5849-4b6b-be25-7a41c0bae880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular ng-scope</value>
      <webElementGuid>ebbd8296-5135-4448-923e-187aa5b0fc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Thank_you_for_buying_with_Advantage</value>
      <webElementGuid>cda531e3-41b4-4cdc-bbf9-2f71943d2580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for buying with Advantage</value>
      <webElementGuid>abe022a2-f819-46de-b863-02258f9b836a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderPaymentSuccess&quot;)/h2[1]/span[@class=&quot;roboto-regular ng-scope&quot;]</value>
      <webElementGuid>cc50db0d-34ca-4e90-b0a3-309a854fc81f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']/h2/span</value>
      <webElementGuid>9500b6d0-561d-47e4-b67d-59737a7a0280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>f502bc86-0a32-4953-a642-53a819b0eb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Thank you for buying with Advantage' or . = 'Thank you for buying with Advantage')]</value>
      <webElementGuid>ac694630-e41c-46a7-b742-d2b7bab2825a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
