<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UsernameUsername</name>
   <tag></tag>
   <elementGuidId>9ea5eff3-3f3b-4064-a44a-5cfc2918d6cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.spliter > sec-view.ng-isolate-scope.sec-view > div.inputContainer.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formCover']/div/div/sec-view/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d96b4421-c351-4f7a-8d59-0b6b7b8d582f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputContainer ng-scope</value>
      <webElementGuid>8d062321-f3ea-4a4d-a66b-03b432c31ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*UsernameUsername</value>
      <webElementGuid>50a5c38c-402a-4a50-9c9c-79c4afaf25d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCover&quot;)/div[1]/div[@class=&quot;spliter&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]</value>
      <webElementGuid>814a01ab-f38b-40b2-ade6-c85aa7f8e5a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCover']/div/div/sec-view/div</value>
      <webElementGuid>f2b765cb-27aa-4f9e-b77c-90e4436a6610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/sec-view/div</value>
      <webElementGuid>18d10f57-6749-4b69-a0c3-9c61bd4b1143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '*UsernameUsername' or . = '*UsernameUsername')]</value>
      <webElementGuid>a47cb7d7-d9aa-4f4d-a67b-196aae7fca82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
