<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SEND</name>
   <tag></tag>
   <elementGuidId>bde2c6a5-b01d-4b38-9dc9-7c65a1e462e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='send_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f48fa810-8381-4872-97cd-810a14a524d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send_btn</value>
      <webElementGuid>3996d118-2179-416d-b0e8-a5ac76b50413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ead152fc-b687-4d97-a392-0adc8bd04166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sec-sender-a ng-scope</value>
      <webElementGuid>72b7d212-5739-4ee6-80a7-90920b200221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94cd6842-dcb4-4d7d-92e5-f6035278accd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>senderCtrl.send()</value>
      <webElementGuid>3b8b482e-52b8-4c06-bd2a-1d7c04c84b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEND</value>
      <webElementGuid>3513e814-ca32-414c-b063-b29039db6ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send_btn&quot;)</value>
      <webElementGuid>00d10e1e-4588-40ba-9db7-f4120e418ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='send_btn']</value>
      <webElementGuid>6a511d71-b352-42db-ba3d-e50e4099f779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supportCover']/div[2]/sec-form/div[2]/div/sec-sender/button</value>
      <webElementGuid>d10a5e35-38f8-43c4-a493-ef6a529765c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/sec-sender/button</value>
      <webElementGuid>8f7b1799-9364-4890-831c-0261a037f4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'send_btn' and @type = 'button' and (text() = 'SEND' or . = 'SEND')]</value>
      <webElementGuid>2746956c-0879-4c75-a2f8-bc9f53c1d817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
