<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select ProductHP Chromebook 14 G1(EN_361ba3</name>
   <tag></tag>
   <elementGuidId>f988db0d-3bcf-4c51-badd-6223a825941b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;productListboxContactUs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='productListboxContactUs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2d15e16d-ca28-4954-9bc9-87cc0b5d770f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-init</name>
      <type>Main</type>
      <value>secModel = secSelectOptions[0]</value>
      <webElementGuid>41618b02-1b51-410d-bf53-6bac88bd608a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>productListboxContactUs</value>
      <webElementGuid>1201197e-705b-4cde-addf-b44b42b2c9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>5006bf5a-0164-4948-af8c-8d83875f99e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>42037686-95db-48ab-b88c-e4ec6f540f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>c as c.productName for c in secSelectOptions</value>
      <webElementGuid>8e0e16a1-3ca0-4c8e-85f8-dd088b60bd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-scope in-focus ng-touched</value>
      <webElementGuid>bc308903-7a07-4bdf-920d-e1576286a74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ProductHP Chromebook 14 G1(ENERGY STAR)HP Chromebook 14 G1(ES)HP ENVY - 17t Touch LaptopHP ENVY x360 - 15t LaptopHP Pavilion 15t Touch LaptopHP Pavilion 15z LaptopHP Pavilion 15z Touch LaptopHP Pavilion x360 - 11t Touch LaptopHP Spectre x360 - 13-4102dxHP Stream - 11-d020nr LaptopHP ZBook 17 G2 Mobile Workstation</value>
      <webElementGuid>07647cb7-90a4-4227-84bb-4af8369890d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supportCover&quot;)/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;splitter&quot;]/div[@class=&quot;inputMargin&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/select[@class=&quot;ng-pristine ng-valid ng-scope in-focus ng-touched&quot;]</value>
      <webElementGuid>f1aabb2a-7760-46a1-acb5-e899048de43a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='productListboxContactUs']</value>
      <webElementGuid>57025987-822a-4d78-9f4a-469b0d4521e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supportCover']/div[2]/sec-form/div/div/sec-view[2]/div/select</value>
      <webElementGuid>b1419de3-8627-401c-b07f-9b796a9e3ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sec-view[2]/div/select</value>
      <webElementGuid>e7c17994-edf1-4dc8-9448-d8317e0e0715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'productListboxContactUs' and (text() = 'Select ProductHP Chromebook 14 G1(ENERGY STAR)HP Chromebook 14 G1(ES)HP ENVY - 17t Touch LaptopHP ENVY x360 - 15t LaptopHP Pavilion 15t Touch LaptopHP Pavilion 15z LaptopHP Pavilion 15z Touch LaptopHP Pavilion x360 - 11t Touch LaptopHP Spectre x360 - 13-4102dxHP Stream - 11-d020nr LaptopHP ZBook 17 G2 Mobile Workstation' or . = 'Select ProductHP Chromebook 14 G1(ENERGY STAR)HP Chromebook 14 G1(ES)HP ENVY - 17t Touch LaptopHP ENVY x360 - 15t LaptopHP Pavilion 15t Touch LaptopHP Pavilion 15z LaptopHP Pavilion 15z Touch LaptopHP Pavilion x360 - 11t Touch LaptopHP Spectre x360 - 13-4102dxHP Stream - 11-d020nr LaptopHP ZBook 17 G2 Mobile Workstation')]</value>
      <webElementGuid>bf2b3287-e735-4fbb-bc9a-d9fc2731b0d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
