<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select ProductBeats Studio 2 Over-Ea_81bad4</name>
   <tag></tag>
   <elementGuidId>65b95b7a-05a7-4eb6-b660-35428e47d689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;productListboxContactUs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='productListboxContactUs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f1ad90f6-3719-41b1-8d10-eaab9087b0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-init</name>
      <type>Main</type>
      <value>secModel = secSelectOptions[0]</value>
      <webElementGuid>c6da0292-018e-4be8-a46b-f64f8386a738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>productListboxContactUs</value>
      <webElementGuid>ce0bb679-97d2-4377-bbe2-c3bfdbe4663f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>c0d26387-208b-452a-b0f2-c72b2f9bd6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>1308ce12-e92d-4e6a-afa0-206b3800a8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>c as c.productName for c in secSelectOptions</value>
      <webElementGuid>fcbe1ddc-5b1a-4962-b4d2-58f3d572ee81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-scope in-focus ng-dirty ng-touched</value>
      <webElementGuid>5333d8f4-8ea2-4f48-acff-a010ad262ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ProductBeats Studio 2 Over-Ear Matte Black HeadphonesBose SoundLink Around-ear Wireless Headphones IIgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesHP H2310 In-ear HeadsetLogitech USB Headset H390</value>
      <webElementGuid>23e09ed0-e71a-4741-96b6-918bb5abd269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supportCover&quot;)/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;splitter&quot;]/div[@class=&quot;inputMargin&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/select[@class=&quot;ng-valid ng-scope in-focus ng-dirty ng-touched&quot;]</value>
      <webElementGuid>2ed7ed9e-5e6b-45c2-9765-9e1c5bc261cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='productListboxContactUs']</value>
      <webElementGuid>8a72800c-9f71-45f8-8c1a-767051380818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supportCover']/div[2]/sec-form/div/div/sec-view[2]/div/select</value>
      <webElementGuid>74ff9fd0-b5a4-4170-afab-3000d56d6d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sec-view[2]/div/select</value>
      <webElementGuid>fc86cdfc-f88f-49e7-a35a-0c0c5bd88aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'productListboxContactUs' and (text() = 'Select ProductBeats Studio 2 Over-Ear Matte Black HeadphonesBose SoundLink Around-ear Wireless Headphones IIgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesHP H2310 In-ear HeadsetLogitech USB Headset H390' or . = 'Select ProductBeats Studio 2 Over-Ear Matte Black HeadphonesBose SoundLink Around-ear Wireless Headphones IIgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesgame of thronesHP H2310 In-ear HeadsetLogitech USB Headset H390')]</value>
      <webElementGuid>244e5729-484d-43f6-b7aa-477d0a2abd88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
