<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select ProductBose Soundlink Bluetoo_1f9d77</name>
   <tag></tag>
   <elementGuidId>539e2b35-3bb0-4435-8754-efc25c002b54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;productListboxContactUs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='productListboxContactUs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ce5fa86-8317-4dca-9fac-fe19183a6bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-init</name>
      <type>Main</type>
      <value>secModel = secSelectOptions[0]</value>
      <webElementGuid>42e331bf-d59e-44e2-8010-32a748e91a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>productListboxContactUs</value>
      <webElementGuid>f543aec9-8064-43e9-853d-0b6b8b9d17ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>5b57d7f9-d3e8-43d0-b375-aff79b214607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>8e96cd6d-b34b-440d-b496-af6616407cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>c as c.productName for c in secSelectOptions</value>
      <webElementGuid>da09ea48-0c04-456e-ae3b-c8015fa7e7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-scope in-focus ng-dirty ng-touched</value>
      <webElementGuid>ad1ccce8-d861-4b95-a045-3afea2acdefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ProductBose Soundlink Bluetooth Speaker IIIBose SoundLink Wireless SpeakerHP Roar Mini Wireless SpeakerHP Roar Plus Wireless SpeakerHP Roar Wireless SpeakerHP S9500 Bluetooth Wireless SpeakerLogitech X100 Speaker System - Wireless Speaker(s)</value>
      <webElementGuid>d4554afb-a39a-4068-9664-8e13d29320e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supportCover&quot;)/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;splitter&quot;]/div[@class=&quot;inputMargin&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/select[@class=&quot;ng-valid ng-scope in-focus ng-dirty ng-touched&quot;]</value>
      <webElementGuid>5be6a195-8acb-4e9a-8ab7-198eb6f7441e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='productListboxContactUs']</value>
      <webElementGuid>a7dd1340-1bc4-4800-b541-19e0aaf63f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supportCover']/div[2]/sec-form/div/div/sec-view[2]/div/select</value>
      <webElementGuid>1e9c6a17-4c81-4ec7-98e7-76821107f70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sec-view[2]/div/select</value>
      <webElementGuid>9d0dcc20-77b1-4b4a-92a9-ccb428962145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'productListboxContactUs' and (text() = 'Select ProductBose Soundlink Bluetooth Speaker IIIBose SoundLink Wireless SpeakerHP Roar Mini Wireless SpeakerHP Roar Plus Wireless SpeakerHP Roar Wireless SpeakerHP S9500 Bluetooth Wireless SpeakerLogitech X100 Speaker System - Wireless Speaker(s)' or . = 'Select ProductBose Soundlink Bluetooth Speaker IIIBose SoundLink Wireless SpeakerHP Roar Mini Wireless SpeakerHP Roar Plus Wireless SpeakerHP Roar Wireless SpeakerHP S9500 Bluetooth Wireless SpeakerLogitech X100 Speaker System - Wireless Speaker(s)')]</value>
      <webElementGuid>f601f7d1-1021-439a-8e37-1ae3e0f7c201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
