<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select ProductHP USB 3 Button Optica_4aac91</name>
   <tag></tag>
   <elementGuidId>7d0ff280-de79-415a-8cf8-f3a76701fd49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;productListboxContactUs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='productListboxContactUs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e58242a0-75de-4383-a27c-a9903dd6e5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-init</name>
      <type>Main</type>
      <value>secModel = secSelectOptions[0]</value>
      <webElementGuid>9e8b3672-d0b3-4417-b931-19adb6475fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>productListboxContactUs</value>
      <webElementGuid>bc20708e-873b-4e24-828c-3dad5ec2da92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>f69bdbae-90a6-44fa-b57c-f54432ac0e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>f83c5c6d-16f7-4322-bd75-e4addd2d9031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>c as c.productName for c in secSelectOptions</value>
      <webElementGuid>6e1a65e4-5ad6-434e-9d2a-1bf1bb192122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope in-focus</value>
      <webElementGuid>338105ea-0008-427a-a267-33f3e97366c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ProductHP USB 3 Button Optical MouseHP Z3200 Wireless MouseHP Z3600 Wireless MouseHP Z4000 Wireless MouseHP Z8000 Bluetooth MouseKensington Orbit 72337 Trackball with Scroll RingKensington Orbit 72352 TrackballLogitech G502 Proteus CoreMicrosoft Sculpt Touch Mouse</value>
      <webElementGuid>f659b86b-86ea-4b17-8848-99239907ff41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supportCover&quot;)/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;splitter&quot;]/div[@class=&quot;inputMargin&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/select[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope in-focus&quot;]</value>
      <webElementGuid>87ab2737-a331-4622-bfa2-18ef6a3dfba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='productListboxContactUs']</value>
      <webElementGuid>f18ee6f9-2de0-4785-be9a-97e3d75c0f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supportCover']/div[2]/sec-form/div/div/sec-view[2]/div/select</value>
      <webElementGuid>7fb38a94-0e40-4d9c-8f89-a1036f638abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sec-view[2]/div/select</value>
      <webElementGuid>c109b26e-61e7-4b13-8e71-bf6b6bb9793c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'productListboxContactUs' and (text() = 'Select ProductHP USB 3 Button Optical MouseHP Z3200 Wireless MouseHP Z3600 Wireless MouseHP Z4000 Wireless MouseHP Z8000 Bluetooth MouseKensington Orbit 72337 Trackball with Scroll RingKensington Orbit 72352 TrackballLogitech G502 Proteus CoreMicrosoft Sculpt Touch Mouse' or . = 'Select ProductHP USB 3 Button Optical MouseHP Z3200 Wireless MouseHP Z3600 Wireless MouseHP Z4000 Wireless MouseHP Z8000 Bluetooth MouseKensington Orbit 72337 Trackball with Scroll RingKensington Orbit 72352 TrackballLogitech G502 Proteus CoreMicrosoft Sculpt Touch Mouse')]</value>
      <webElementGuid>e28d7b49-82be-4c8f-abec-f67be52d47e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
